import { Dark } from '@/lib/darkTheme';

const shared = {
  text: Dark.text,
  background: Dark.bgSoft,
  backgroundAlt: Dark.bg,
  tint: Dark.lime,
  tabIconDefault: '#636366',
  tabIconSelected: Dark.lime,
  accent: Dark.lime,
  accentSoft: Dark.limeSoft,
  lime: Dark.lime,
  card: Dark.card,
  cardElevated: Dark.cardElevated,
  muted: Dark.textMuted,
  border: Dark.border,
  cardHover: Dark.cardHover,
  success: Dark.success,
  warning: Dark.warning,
  danger: Dark.danger,
  info: Dark.info,
  teal: Dark.lime,
  tabBar: Dark.tabBar,
  tabBarText: Dark.text,
  onAccent: Dark.bg,
  overlay: 'rgba(0,0,0,0.55)',
  gradientStart: Dark.card,
  gradientEnd: Dark.bg,
  heroGradient: [Dark.cardElevated, Dark.bg] as const,
  screenGradient: [Dark.bgSoft, Dark.bg, Dark.bgSoft] as const,
  glow: Dark.limeGlow,
  pastelMint: Dark.limeSoft,
  pastelBlue: Dark.cardHover,
  pastelPink: Dark.card,
  pastelYellow: Dark.limeSoft,
  pastelLavender: Dark.cardElevated,
  pastelPeach: Dark.cardHover,
};

export default {
  light: { ...shared },
  dark: { ...shared },
} as const;
